# Generated by Django 4.2.4 on 2023-08-17 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfirstapp', '0002_inputform'),
    ]

    operations = [
        migrations.AddField(
            model_name='inputform',
            name='food_service',
            field=models.CharField(choices=[('1', 'Delivery'), ('2', 'Order In'), ('3', 'Take out')], default='Delivery', max_length=200),
        ),
    ]
