# Generated by Django 4.2.4 on 2023-08-18 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfirstapp', '0003_inputform_food_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inputform',
            name='time_log',
        ),
        migrations.AddField(
            model_name='inputform',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='inputform',
            name='food_service',
            field=models.CharField(choices=[('Delivery', 'Delivery'), ('Order In', 'Order In'), ('Take out', 'Take out')], default='Delivery', max_length=200),
        ),
    ]
