# Generated by Django 4.2.4 on 2023-08-21 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfirstapp', '0005_reservation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
